[package]
name = "blockchain_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
hex = "0.4.3"
typenum = "1.15.0"
primitive-types = "0.11.1"
